library(dplyr)
library(hoopR)
skies <- kp_team_players('Connecticut',2023)
canes <- kp_team_players('Miami FL',2023)
uconn_reb_num <- skies %>% filter(role!='Benchwarmer') %>% select(player,number,min_pct,or_pct,dr_pct) 
miami_reb_num <- canes %>% filter(role!='Benchwarmer') %>% select(player,number,min_pct,or_pct,dr_pct)
pdf('/Users/mileskee7/Desktop/College/Senior Year/W/graph.pdf')
plot(uconn_reb_num$or_pct,uconn_reb_num$dr_pct,type='n',main = 'Rebounding Percentages by Player',xlab='Offensive Rebounding %',ylab='Defensive Rebounding %')
text(uconn_reb_num$or_pct,uconn_reb_num$dr_pct,labels=uconn_reb_num$number,cex=.8,col='blue')
text(miami_reb_num$or_pct,miami_reb_num$dr_pct,labels=miami_reb_num$number,cex=.8,col='green')
legend('topright',legend=c('UConn','Miami'),fill=c('blue','green'))
dev.off()

days <- c('Sunday','Monday','Tuesday','Wednesday','Thursday')
hours <- c(7,6,6,4,5)
table <- data.frame(days,hours)
